//GET http://localhost:3000/api/users

//GET http://localhost:3000/api/users/2

//POST http://localhost:3000/api/users
//Content-Type: application/json

//{
  //"name": "Kapri",
  //"salary": 30000
//}

//DELETE http://localhost:3000/api/users/10

PATCH http://localhost:3000/api/users/2
Content-Type: application/json

{
  "name": "Milu",
  "salary": 50000
}



